### ISSUE TITLE
Github Action fails  - error getting a locales package?

### ISSUE THREAD

**Issue by acidjazz** [dave/courtney#30]
I'm not quite sure where this is coming from since GH is definitely not down:

here is the area where i install/run courtney:

```yaml
      - name: Install courtney for coverage
        run: go install github.com/dave/courtney@latest

      - name: Run Tests
        run: |
          courtney ./tests ./controllers
```

and my output is now oddly:

```
Run courtney ./tests ./controllers
open  downloading github.com/go-playground/locales v0.[1](https://github.com/vulncheck/api/actions/runs/3166862695/jobs/5156898345#step:12:1)4.0: no such file or directory
Error reading files from  downloading github.com/go-playground/locales v0.14.0
github.com/dave/courtney/tester.(*Tester).processDir
	/home/runner/go/pkg/mod/github.com/dave/courtney@v0.4.0/tester/tester.go:1[9](https://github.com/vulncheck/api/actions/runs/3166862695/jobs/5156898345#step:12:10)5
github.com/dave/courtney/tester.(*Tester).Test
	/home/runner/go/pkg/mod/github.com/dave/courtney@v0.4.0/tester/tester.go:59
main.Run
	/home/runner/go/pkg/mod/github.com/dave/courtney@v0.4.0/courtney.go:66
main.main
	/home/runner/go/pkg/mod/github.com/dave/courtney@v0.4.0/courtney.go:44
runtime.main
	/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/proc.go:250
runtime.goexit
	/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/asm_amd64.s:[15](https://github.com/vulncheck/api/actions/runs/3166862695/jobs/5156898345#step:12:16)94
Test
main.Run
	/home/runner/go/pkg/mod/github.com/dave/courtney@v0.4.0/courtney.go:67
main.main
	/home/runner/go/pkg/mod/github.com/dave/courtney@v0.4.0/courtney.go:44
runtime.main
	/opt/hostedtoolcache/go/1.[19](https://github.com/vulncheck/api/actions/runs/3166862695/jobs/5156898345#step:12:20).1/x64/src/runtime/proc.go:250
runtime.goexit
	/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/asm_amd64.s:1594
```
